/**
 * hooks/mcp_verifier_server.js  (updated)
 *
 * MCP tool server: Legacy C++ Engine Static Audit
 *
 * Tools:
 *   run_legacy_engine_audit  — runs backend/verify_legacy_engine.sh, returns full output
 *   read_defect_report       — reads defect_report.json if present
 *   read_verify_log          — reads verify_run.log if present
 *
 * Defects characterized: FP-001, SOL-002, LAT-003, LOG-005, SYN-004
 * Source files analyzed: backend/legacy_core_engine.cpp
 *
 * HARNESS CONTRACT: These tools PASS when defects are present (proving they exist).
 * They are for characterization, not remediation.
 *
 * SECURITY: No credentials required. Never logs sensitive values.
 */

"use strict";

const readline = require("readline");
const { execFile } = require("child_process");
const fs = require("fs");
const path = require("path");

const WORKSPACE_ROOT = path.resolve(__dirname, "..");
const BACKEND_DIR    = path.join(WORKSPACE_ROOT, process.env.BACKEND_DIR || "backend");
const VERIFY_SCRIPT  = path.join(BACKEND_DIR, "verify_legacy_engine.sh");
const DEFECT_REPORT  = path.join(WORKSPACE_ROOT, "defect_report.json");
const VERIFY_LOG     = path.join(WORKSPACE_ROOT, "verify_run.log");

const rl = readline.createInterface({ input: process.stdin, terminal: false });
let buffer = "";

rl.on("line", (line) => {
  buffer += line;
  try { const msg = JSON.parse(buffer); buffer = ""; handleMessage(msg); }
  catch { /* partial */ }
});

function send(obj) { process.stdout.write(JSON.stringify(obj) + "\n"); }

function handleMessage(msg) {
  if (msg.method === "initialize") {
    send({ jsonrpc: "2.0", id: msg.id, result: {
      protocolVersion: "2024-11-05",
      serverInfo: { name: "legacyengine-verifier", version: "2.0.0" },
      capabilities: { tools: {} },
    }});
    return;
  }

  if (msg.method === "tools/list") {
    send({ jsonrpc: "2.0", id: msg.id, result: { tools: [
      {
        name: "run_legacy_engine_audit",
        description:
          "Runs backend/verify_legacy_engine.sh against legacy_core_engine.cpp. " +
          "Returns grep-based analysis for FP-001 (double monetary fields), " +
          "SOL-002 (no hard stop on solvency breach), LAT-003 (blocking sleep), " +
          "SYN-004 (missing semicolon), LOG-005 (fee not applied), and a " +
          "compilation check. HARNESS CONTRACT: FAIL output means the defect is " +
          "present and confirmed — this is the expected characterization result.",
        inputSchema: { type: "object", properties: {}, required: [] },
      },
      {
        name: "read_defect_report",
        description: "Returns contents of defect_report.json (generated by last audit run). Never edit this file by hand.",
        inputSchema: { type: "object", properties: {}, required: [] },
      },
      {
        name: "read_verify_log",
        description: "Returns contents of verify_run.log (generated by last audit run).",
        inputSchema: { type: "object", properties: {}, required: [] },
      },
    ]}});
    return;
  }

  if (msg.method === "tools/call") {
    const name = msg.params && msg.params.name;
    if (name === "run_legacy_engine_audit") return toolRunVerify(msg);
    if (name === "read_defect_report") return toolReadFile(msg, DEFECT_REPORT, "defect_report.json");
    if (name === "read_verify_log")    return toolReadFile(msg, VERIFY_LOG, "verify_run.log");
    send({ jsonrpc: "2.0", id: msg.id, error: { code: -32601, message: `Unknown tool: ${name}` } });
    return;
  }

  send({ jsonrpc: "2.0", id: msg.id, error: { code: -32601, message: `Method not found: ${msg.method}` } });
}

function toolRunVerify(msg) {
  // Run verify script from the backend directory so relative paths resolve.
  execFile("bash", [VERIFY_SCRIPT, "legacy_core_engine.cpp"],
    { cwd: BACKEND_DIR, timeout: 60000 },
    (err, stdout, stderr) => {
      const exitCode = err ? (err.code || 1) : 0;
      const combined = (stdout || "") + (stderr ? "\n[stderr]\n" + stderr : "");
      // Write a minimal defect_report.json for downstream consumers.
      const report = {
        generated_at: new Date().toISOString(),
        exit_code: exitCode,
        expected_defects: ["FP-001", "SOL-002", "LAT-003", "LOG-005", "SYN-004"],
        raw_output_lines: combined.split("\n").length,
        note: "HARNESS PASS: FAIL lines in output confirm defects are present. Do not fix source yet.",
      };
      try { fs.writeFileSync(DEFECT_REPORT, JSON.stringify(report, null, 2)); } catch {}
      send({ jsonrpc: "2.0", id: msg.id, result: {
        content: [{ type: "text", text: `Exit code: ${exitCode}\n\n${combined}` }],
      }});
    }
  );
}

function toolReadFile(msg, filePath, label) {
  let content;
  try { content = fs.readFileSync(filePath, "utf8"); }
  catch { content = `[${label} not found — run run_legacy_engine_audit first]`; }
  send({ jsonrpc: "2.0", id: msg.id, result: { content: [{ type: "text", text: content }] } });
}
